apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: busybox
    image: busybox:latest
    command: ["sleep", "3600"]
    ports:
    - containerPort: 8080